version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
    depends_on:
        db:
          condition: service_healthy
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=Proyecto1
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d Proyecto1"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 